/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#2563EB',
        'primary-hover': '#1d4ed8',
        'primary-dark': '#1d4ed8',
        secondary: '#1E40AF',
        'secondary-light': '#3B82F6',
        danger: '#EF4444',
        success: '#10B981',
        warning: '#F59E0B',
        'background-light': '#F3F4F6',
        'background-dark': '#111827',
        'surface-light': '#FFFFFF',
        'surface-dark': '#1F2937',
        'card-light': '#FFFFFF',
        'card-dark': '#1F2937',
        'text-light': '#111827',
        'text-dark': '#F9FAFB',
        'text-muted-light': '#6b7280',
        'text-muted-dark': '#9ca3af',
        'text-primary-light': '#111827',
        'text-primary-dark': '#F9FAFB',
        'text-secondary-light': '#6B7280',
        'text-secondary-dark': '#9CA3AF',
        'secondary-text-light': '#6B7280',
        'secondary-text-dark': '#9CA3AF',
        'border-light': '#E5E7EB',
        'border-dark': '#374151',
        'subtext-light': '#6B7280',
        'subtext-dark': '#9CA3AF',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        glow: '0 0 20px rgba(37, 99, 235, 0.3)',
        soft: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
      },
    },
  },
  plugins: [],
};
