export const CATEGORY_ICONS: Record<string, string> = {
  'Food & Dining': 'restaurant',
  Transportation: 'directions_car',
  Utilities: 'bolt',
  Entertainment: 'movie',
  Healthcare: 'local_hospital',
  Shopping: 'shopping_bag',
  Education: 'school',
  'Housing & Rent': 'home',
  'Personal Care': 'self_improvement',
  Travel: 'flight',
  Subscriptions: 'subscriptions',
  'Fitness & Wellness': 'fitness_center',
  'Gifts & Donations': 'card_giftcard',
  Insurance: 'health_and_safety',
  'Taxes & Fees': 'receipt_long',
  Other: 'category',
};

export const CATEGORY_COLORS: Record<string, string> = {
  'Food & Dining': 'bg-orange-500',
  Transportation: 'bg-blue-500',
  Utilities: 'bg-yellow-500',
  Entertainment: 'bg-purple-500',
  Healthcare: 'bg-red-500',
  Shopping: 'bg-pink-500',
  Education: 'bg-teal-500',
  'Housing & Rent': 'bg-lime-500',
  'Personal Care': 'bg-rose-400',
  Travel: 'bg-cyan-500',
  Subscriptions: 'bg-violet-500',
  'Fitness & Wellness': 'bg-emerald-500',
  'Gifts & Donations': 'bg-amber-400',
  Insurance: 'bg-sky-500',
  'Taxes & Fees': 'bg-slate-500',
  Other: 'bg-gray-500',
};
